spring.application.name=chat-ai
server.port=8080

# Spring AI Ollama configuration
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.2:1b
spring.ai.ollama.chat.options.temperature=0.7

logging.level.org.springframework.ai=INFO
